# Generated by Django 5.2.6 on 2025-12-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='provider_photos/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provider_logos/')),
                ('rating', models.FloatField(default=0)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_cities', models.CharField(blank=True, max_length=255)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='provider_id_docs/')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='provider_license_docs/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='provider_insurance_docs/')),
                ('background_check_status', models.CharField(blank=True, max_length=32)),
                ('payout_method', models.CharField(blank=True, choices=[('bank', 'Bank'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('payout_details', models.TextField(blank=True)),
                ('commission_percentage', models.FloatField(default=0)),
                ('availability_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('scheduled', 'Scheduled')], default='offline', max_length=20)),
                ('response_time_avg', models.FloatField(default=0)),
                ('cancellation_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_categories', models.ManyToManyField(related_name='providers', to='service_category.servicecategory')),
            ],
        ),
    ]
