# Generated by Django 5.2.6 on 2025-12-21 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='adverts/')),
                ('caption', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_method', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('drivers_license', models.FileField(blank=True, null=True, upload_to='verification_docs/drivers_license/')),
                ('car_ownership', models.FileField(blank=True, null=True, upload_to='verification_docs/car_ownership/')),
                ('car_image_1', models.ImageField(blank=True, null=True, upload_to='verification_docs/car_images/')),
                ('car_image_2', models.ImageField(blank=True, null=True, upload_to='verification_docs/car_images/')),
                ('inspection_report', models.FileField(blank=True, null=True, upload_to='verification_docs/inspection_report/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='driver_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='driver_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
