# Generated by Django 5.2.6 on 2025-12-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0004_alter_customer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Admin notes for approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
    ]
