# Generated by Django 5.2.6 on 2025-12-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0005_driver_approval_notes_driver_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Driver online/offline status'),
        ),
    ]
