# Generated by Django 5.2.6 on 2026-01-05 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0006_driver_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('ride_type', models.CharField(choices=[('standard', 'MOVE Standard'), ('xl', 'MOVE XL'), ('premium', 'MOVE Premium')], max_length=20)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('mobilemoney', 'Mobile Money')], max_length=20)),
                ('payment_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='corporate.driver')),
            ],
        ),
    ]
