# Generated by Django 5.2.6 on 2026-01-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0008_booking_completed_at_booking_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
    ]
