# Generated by Django 5.2.6 on 2026-01-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0009_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Optional contact name for this ride', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Optional contact phone for this ride', max_length=20, null=True),
        ),
    ]
