# Generated by Django 5.2.6 on 2026-01-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0011_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='number_of_cars',
            field=models.IntegerField(default=1, help_text='Number of cars required'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='total_passengers',
            field=models.IntegerField(default=4, help_text='Total number of passengers (4 per car)'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Total price for all cars', max_digits=10),
            preserve_default=False,
        ),
    ]
