# Generated by Django 5.2.6 on 2026-01-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0014_alter_servicebooking_provider_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from driver to pickup in km', max_digits=10, null=True)),
                ('driver_score', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated score for this driver', max_digits=10, null=True)),
                ('offer_order', models.IntegerField(default=1, help_text='Order in which this offer was sent (1=first)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this offer expires')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When driver responded', null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_offers', to='corporate.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_offers', to='corporate.driver')),
            ],
            options={
                'ordering': ['-offered_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('booking',), name='unique_pending_offer_per_booking')],
            },
        ),
    ]
