# Generated by Django 5.2.6 on 2026-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0017_update_coordinate_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Average driver rating (1-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings received'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_trips',
            field=models.PositiveIntegerField(default=0, help_text='Total completed trips'),
        ),
    ]
