# Generated by Django 5.2.6 on 2026-01-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0019_add_driver_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle license plate number', max_length=20, null=True),
        ),
    ]
