# Generated by Django 5.2.6 on 2026-01-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0020_driver_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Expo push notification token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Expo push notification token', max_length=255, null=True),
        ),
    ]
