# Generated by Django 5.2.6 on 2026-01-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0021_customer_expo_push_token_driver_expo_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MOVE', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
