# Generated by Django 5.2.6 on 2025-12-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_category', '0001_initial'),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pricing_type', models.CharField(choices=[('flat', 'Flat'), ('per_km', 'Per KM'), ('per_hour', 'Per Hour'), ('package', 'Package')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('booking_mode', models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20)),
                ('min_advance_booking_minutes', models.PositiveIntegerField(default=0)),
                ('cancellation_window_minutes', models.PositiveIntegerField(default=0)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_passengers', models.PositiveIntegerField(default=1)),
                ('max_luggage', models.PositiveIntegerField(default=0)),
                ('vehicle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('vehicle_features', models.CharField(blank=True, max_length=255)),
                ('inspection_required', models.BooleanField(default=False)),
                ('available_cities', models.CharField(blank=True, max_length=255)),
                ('available_days', models.CharField(blank=True, max_length=100)),
                ('available_start_time', models.TimeField(blank=True, null=True)),
                ('available_end_time', models.TimeField(blank=True, null=True)),
                ('minimum_provider_rating', models.FloatField(default=0)),
                ('priority_score', models.FloatField(default=0)),
                ('required_fields', models.JSONField(blank=True, null=True)),
                ('add_ons', models.JSONField(blank=True, null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='service_category.servicecategory')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='service_provider.serviceprovider')),
            ],
        ),
    ]
