# Generated by Django 5.2.6 on 2025-12-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='service_provided/'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='service_provided/'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='service_provided/'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='service_provided/'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='service_provided/'),
        ),
    ]
